name: mlflow-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas=1.3.5
  - scikit-learn=1.0.2
  - mlflow=1.25.0
  - pip
  - pip:
      - protobuf==3.20.*
      - setuptools==68.2.2
