name: mlflow-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - scikit-learn=1.0.2
  - pandas=1.3.5
  - pip
  - pip:
      - mlflow==1.25.0
      - protobuf==3.20.3  # Versi stabil terakhir yang kompatibel
