# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11R_E2IVFd81P2WPrjmFcgNnOP-VUqFYd

# Import Library
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import mlflow
import mlflow.sklearn

"""# Load Preprocessed Dataset"""

link = 'https://raw.githubusercontent.com/farhatfathi/Eksperimen_SML_Muhammad-Fathi-Farhat/refs/heads/main/preprocessing/df_preprocessed.csv'
df = pd.read_csv(link, delimiter=',')
df = df.drop('CustomerID', axis=1)
df.head()

"""# Modelling"""

X = df.drop("Churn", axis=1)
y = df["Churn"]

# 2. Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Start MLflow experiment
mlflow.set_experiment("churn-prediction")

with mlflow.start_run():
    # 4. Train model
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    # 5. Predict & Evaluate
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    # 6. Logging ke MLflow
    mlflow.log_param("n_estimators", 100)
    mlflow.log_metric("accuracy", acc)
    mlflow.sklearn.log_model(model, "model")

    print(f"Akurasi model: {acc}")