name: Run MLflow Project

on:
  push:
    paths:
      - 'MLproject'
      - '.github/workflows/mlflow-ci.yml'
  workflow_dispatch:

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        activate-environment: mlflow-env
        environment-file: conda.yaml

    - name: Run MLflow project
      run: |
        mlflow run . -P n_estimators=100 --env-manager=local
