name: Run MLflow Project with Docker

on:
  push:
    paths:
      - 'MLproject/**'
      - '.github/workflows/mlflow-ci.yml'
  workflow_dispatch:

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow scikit-learn pandas

      - name: Run MLflow project using Docker
        run: |
          mlflow run . -P n_estimators=100 \
            --env-manager=local \
            --backend=local \
            --build-image
