name: MLflow CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9
          activate-environment: mlflow-env
          environment-file: MLproject/conda.yaml
          auto-activate-base: false

      - name: Run MLflow Project
        run: |
          conda run -n mlflow-env mlflow run . -e main -P n_estimators=100
